data:
  runge_train_path : "./data/runge18train/"
  runge_valid_path : "./data/runge18valid/"
  modena_path      : "./data/modena/"
  eterna_path      : "./data/eterna.txt"
  kauf_train_path  : "./data/kauf_train.txt"
  kauf_valid_path  : "./data/kauf_valid.txt"
C : 1.42
num_simulations : 100
unpaired : ["A", "U", "G", "C"]
paired:    ["AU", "CG", "GC", "UA", "GU", "UG"]
paired_prob  :  {"AU" : 0.33,"CG" : 0.6, "GC" : 0.6, "UA" : 0.33, "GU" : 0.07, "UG" : 0.07}
unpaired_prob : {"A": 0.93, "G": 0.05, "C": 0.01, "U": 0.01}
mutation_threshold: 9
max_sample : 5000
result_path : "./results/"